name: C/C++ Ubuntu-18.04 CI

on:
  push:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo "Linux Kernel is $(uname -r)"
    - name: make
      run: make -j4
